### ISSUE TITLE
Send to printer

### ISSUE THREAD

**Issue by phate82** [NielsLeenheer/EscPosEncoder#1]
Hi,
how can I send the resulting encoding to the printer?
Thanks

**Comment by NielsLeenheer** [comment]
Sending data to the printer is not within the scope of this library and can depend on how the device is connected. 

It could be:
- opening a serial port for a serial connected printer (or USB or Classic Bluetooth with a virtual serial port driver)
- opening a network socket to an ip address for a network connected printer
- talking directly to an USB printer
- or using Bluetooth LE and write the data to a specific characteristic for BLE printers.

Right now this is still your own responsibility. This library will only give you the data that you need to send to the printer. In the future I may create a library for sending the data, but it will be separate from this library. 

An example of how this library is used for a Bluetooth LE printer using the WebBluetooth API in the browser can be found here: https://github.com/BluetoothRocks/TweetPrinter

**Comment by phate82** [comment]
Thanks a lot for your quick answer!
Currently, I'm using this library for encoding and sending data to my esc-pos printer:

https://github.com/song940/node-escpos

anyway, I'd like to try your library since it seems to provide more options. I was thought that it could be possible to send the result of your encoding through the aforementioned library..but, unfortunately, I don't think so. I have to search another solution for trying your library.
