### ISSUE TITLE
print an image in react-native

### ISSUE THREAD

**Issue by tareqwaisi** [NielsLeenheer/EscPosEncoder#12]
Hi,
First of all, thanks very much for your package.
It is great!
I am trying to print an image via react-native, but I don't know how to define a suitable argument (img) for the image function in react-native.
.image(img, 300, 300, 'atkinson').
As far as I know, we can include images in react-native via one of the following codes:
would you be able to help me?
Thanks

        <Image
          source={require('/react-native/img/favicon.png')}
        />
        <Image
          style={{width: 50, height: 50}}
          source={{uri: 'https://facebook.github.io/react-native/docs/assets/favicon.png'}}
        />
        <Image
          style={{width: 66, height: 58}}
          source={{uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADMAAAAzCAYAAAA6oTAqAAAAEXRFWHRTb2Z0d2FyZQBwbmdjcnVzaEB1SfMAAABQSURBVGje7dSxCQBACARB+2/ab8BEeQNhFi6WSYzYLYudDQYGBgYGBgYGBgYGBgYGBgZmcvDqYGBgmhivGQYGBgYGBgYGBgYGBgYGBgbmQw+P/eMrC5UTVAAAAABJRU5ErkJggg=='}}
        />

**Comment by xeb10154** [comment]
Hi, does this even work in react-native? I've been looking at various packages and none of them seem to support react-native. Do you have a got repo with examples? Much appreciated. Thanks.

**Comment by FazilMuhammed** [comment]
@xeb10154 @tareqwaisi did you find the solution how to print Image in react-native ??
