### ISSUE TITLE
Print Image with ESC * instead of GS v

### ISSUE THREAD

**Issue by dannygunawan** [NielsLeenheer/EscPosEncoder#16]
Printing text on Epson TM-U220(LAN) works fine, but printing image results garbled text. 

The problem is because this printer does not support GS v command (obsolete). To print image, we have to use ESC * command instead.

If it's possible please add support to this print image feature. Thank you.

Reference: 
(https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=85)

**Comment by NielsLeenheer** [comment]
I'll check if I can support both in an upcoming version.

**Comment by NielsLeenheer** [comment]
The upcoming version 2.0 of EscPosEncoder will support legacy mode (GS v 0) and modern mode (ESC *) for image encoding.
