### ISSUE TITLE
Erro na escrita "coda39"

### ISSUE THREAD

**Issue by ezequiel88** [NielsLeenheer/EscPosEncoder#18]
Após muitos tempo descobri o que causava o erro.
Favor corrigirem

https://github.com/NielsLeenheer/EscPosEncoder/blob/8bfe18c226b543f9a548af64b65077094fd34d70/src/esc-pos-encoder.js#L325

**Comment by NielsLeenheer** [comment]
Will be fixed in the upcoming release.
