### ISSUE TITLE
Error when using EscPosEncoder

### ISSUE THREAD

**Issue by Vartex05** [NielsLeenheer/EscPosEncoder#24]
Hi, iam trzing to use EscPosEncoder for ionic in my ionic 5 app, but iam not able to make it work. I succesfully installed package, import it in my provider, but when i try to use it i get "Unknown Codepage" error, even if iam entering right string for codepage:

`import EscPosEncoder from 'esc-pos-encoder-ionic';

...

  testEncode(){
    let encoder=new EscPosEncoder();
    let result=encoder.codepage('cp852')
    .text('Iñtërnâtiônàlizætiøn')
    .codepage('cp936')
    .text('简体中文')
    .encode();
    console.log(result);
  }

`
Any ideas whats wrong? When i try to run it on mobile device, i get "Runtime compiler is not loaded" Error, when iam trying to access page, to which is my printService provider injected(ESCPosEncoder is imported inside that provider). Iam using ionic 5 with angular 8.2.14

**Comment by Ans0n-Ti0** [comment]
Hello Vertex05,

Try to initialize encoder first

```ts
...
const result = encoder.initialize().codepage('cp852');
...
```
