### ISSUE TITLE
how can i do for loop with EscPosEncoder

### ISSUE THREAD

**Issue by alimuhnad** [NielsLeenheer/EscPosEncoder#27]
this is my code its not working any help
    const encoder = new EscPosEncoder();
    const result = encoder.initialize();
 
    result
    .codepage('iso88596')
      .align('center')
      .raw(commands.TEXT_FORMAT.TXT_4SQUARE)
      .line(this.restname)       
      .newline()
      for (let index = 0; index < this.data.length; index++) {
        const element =  this.data[index];
        result.raw(commands.TEXT_FORMAT.TXT_ALIGN_LT)
        .align('left')
        .line(element['order_number']+'#')
        .raw(commands.TEXT_FORMAT.TXT_ALIGN_RT)
        .align('right')
        .line('رقم الوصل')
        .text(commands.HORIZONTAL_LINE.HR_58MM)
        .newline()
      }
      result.align('center')
      .raw(commands.HORIZONTAL_LINE.HR4_58MM)
      .line(this.phone)       
      .newline()
      .line(this.msg)       

      .newline()
   this.mountAlertBt(result.encode());

**Comment by lajith111** [comment]
@alimuhnad do you find any solution?

**Comment by alimuhnad** [comment]
I made another way using the image

**Comment by lajith111** [comment]
can u pls provide a sample code?thanks

**Comment by mariapaulinar** [comment]
> can u pls provide a sample code?thanks

Maybe this code can help you:

        const encoder = new EscPosEncoder();
        let result = encoder
          .newline()
          .align('center')
          .line('Recibo de caja')
          .newline()
          .newline()
          .align('left')
          .line('-------------------------------')
          .line('TOTAL PAGADO ' + resp.totalPagado)
          .newline()
          .newline()
          .line('Formas Pago')
          .line('-------------------------------');
        for (const item of resp.formasPago) {
          result = result.line(item.tipo + '   $' + item.valor);
        }
        result = result
          .line('-------------------------------')
          .line('TOTAL PAGADO ' + resp.totalPagado)
          .newline()
          .line('Estimado cliente.')
          .line('Su pago lo podrá ver reflejado')
          .line('en el portal de clientes')
          .encode();

**Comment by lajith111** [comment]
@mariapaulinar  thanks a lot  for this code..i wil check,,i  am having another issue when  i send write command to printer ..

it will prints the the data.. and printer is not sending any ackonowment to device and it is auto disconnect..if i send print command after 4 to 5 mins later it only prints... is printer having issue or i dont no in app?do you have any idea ..thanks
```
this.btSerial.connect(macAddress)
    .subscribe(_=>{
     
       this.btSerial.write(resultByte).then( 
     _=>{         
         
          this.alert.presentAlert("succe","Succ"); 
             this.btSerial.disconnect(); 
        },err=>{
          
          this.alert.presentAlert("print",err);  
        }
        
      )},err=>{
    
        this.alert.presentAlert("Connect", err);  
       
    })
```

**Comment by NielsLeenheer** [comment]
It is common for the printer to not give back any feedback after printing. In most cases it is one-way communication. And for Bluetooth printers it is also common to automatically disconnect after certain time. Depends a bit on the printer model.

A good strategy is for every receipt you want to print is to connect, print and disconnect again. 

Another strategy is to make sure the printer stays awake by sending a 'ping' every minute or so. By sending some commands to are harmless, but do make sure the printer does not time out.

```js
let result = encoder
    .raw([ 0x1b, 0x5c, 0x00, 0x00 ])
    .encode()
```

This commands moves the print print position 0 characters to the horizontally and 0 characters vertically. So it basically does nothing.

**Comment by lajith111** [comment]
Thanks you very much @NielsLeenheer.. Actully my issue is btSerial.disconnect();   if i put in subscribe success method it will not print..am confused ..if i commented it will print the data

```
```
 this.btSerial.connect(macAddress)
    .subscribe(_=>{
     
       this.btSerial.write(resultByte).then( 
     _=>{         
         
          this.alert.presentAlert("succe","Succ"); 
        //     this.btSerial.disconnect();        ---if  i  commented it will print & if i  uncommented it will not print in printer
        },err=>{ 
          
          this.alert.presentAlert("print",err);  
        }
```
```
