### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'isEncoding' of undefined

### ISSUE THREAD

**Issue by coolara** [NielsLeenheer/EscPosEncoder#28]
hi i got this error 
ionic5 angular9
many thanks
```  
import EscPosEncoder from 'esc-pos-encoder-ionic';

const encoder = new EscPosEncoder();
this.printDatas = encoder
      .initialize()
      .text('The quick brown fox jumps over the lazy dog')
      .newline()
      .qrcode('https://nielsleenheer.com', 100 , 100, 'h' )
      .encode();

**Comment by Ans0n-Ti0** [comment]
Hello @coolara,

Could you post the error as well?

Anyway, I created a demo application for ionic application for thermal printing. Check it out
https://github.com/Ans0n-Ti0/esc-pos-encoder-ionic-demo

**Comment by NielsLeenheer** [comment]
`esc-pos-encoder-ionic` is not a package that I officially support. You should raise this with the maker of that package.
