### ISSUE TITLE
Does not seem to work with ionic 5

### ISSUE THREAD

**Issue by generalzodo** [NielsLeenheer/EscPosEncoder#29]
core.js:6014 ERROR Error: Uncaught (in promise): ReferenceError: Cannot access 'HomePageModule' before initialization
ReferenceError: Cannot access 'HomePageModule' before initialization

but once I take off the import, app runs smoothly

**Comment by Ans0n-Ti0** [comment]
The error does not seem to relate to ESC/POS library. Maybe you can check out the demo application in github
https://github.com/Ans0n-Ti0/esc-pos-encoder-ionic-demo

**Comment by freecsdevph** [comment]
I also got the same error core.js:4197 ERROR Error: Uncaught (in promise): ReferenceError: Cannot access 'ParkingPageModule' before initialization ReferenceError: Cannot access 'ParkingPageModule' before initialization.

It happens when I put const encoder = new EscPosEncoder();

**Comment by Ans0n-Ti0** [comment]
Seems weird.

Is it possible for you to share your code?
Try to clone https://github.com/Ans0n-Ti0/esc-pos-encoder-ionic-demo and see if it works for the demo project.

**Comment by freecsdevph** [comment]
I tried with the demo project(https://github.com/Ans0n-Ti0/esc-pos-encoder-ionic-demo ) and it is working perfectly. I am trying to look for the difference.

**Comment by freecsdevph** [comment]
Here are the steps that I did to make it work.

1. Copied the package.json dependencies from the demo project
2. Do an npm install
3. Update my project index.html to include 
<script>
  if (global === undefined) {
    var global = window;
  }
</script>

**Comment by pisipisi** [comment]
for me, I'm using on ionic 5, connect to bluetooth printer. I don't know if it my printer or bluetooth library. it's only print from text only, if it has any variable in the text like the code below, it doesn't print.
```
let encoder = new EscPosEncoder();
   encoder = encoder.initialize().align('center');
let result = encoder
    .line(`Thank you ${this.currentStore.name}`, 30)
        .line('Have a wonderful day!')
        .cut()
        .encode();
```
