### ISSUE TITLE
Uncaught Error: Encoding '_sbcs' has incorrect 'chars' 

### ISSUE THREAD

**Issue by PietroGranati** [NielsLeenheer/EscPosEncoder#3]
I'm trying the samples but when I use the text samples I get this error log:

`Uncaught Error: Encoding '_sbcs' has incorrect 'chars' (must be of len 128 or 256)
    at new n (esc-pos-encoder.js:1)
    at Object.s.getCodec (esc-pos-encoder.js:1)
    at Object.s.getEncoder (esc-pos-encoder.js:1)
    at Object.s.encode (esc-pos-encoder.js:1)
    at c._encode (esc-pos-encoder.js:1)
    at c.text (esc-pos-encoder.js:1)
    at testStampa (index.html:8)
    at HTMLButtonElement.onclick (index.html:16)`

**Comment by PietroGranati** [comment]
This is the code called

`let encoder = new EscPosEncoder();
        let result = encoder
        .text('The quick brown fox jumps over the lazy dog', 20)
        .encode()
        console.log(result);`

**Comment by NielsLeenheer** [comment]
Could you execute `npm list iconv-lite` and tell me what version of iconv-lite you have?

**Comment by PietroGranati** [comment]
/Users/mecotest
└── (empty)

I don't know need it

**Comment by NielsLeenheer** [comment]
The iconv-lite library is one of the dependancies of EscPosEncoder. If you installed this library using npm, it should automatically install these dependencies. 

However if you downloaded the code from Github or cloned the repository, you need to manually execute `npm install` in the directory of EscPosEncoder.

**Comment by PietroGranati** [comment]
Ok I've performed a npm install in the directory of escpos, the iconv-lite version is
└── iconv-lite@0.4.23
But same result

**Comment by PietroGranati** [comment]
The qrcode example and the cut works perfectly

**Comment by NielsLeenheer** [comment]
Could you explain a bit more about how you are using this library. For example, are you using a bundler or something like webpack? I ask because it would seem the data files that iconv-lite provide may have become corrupted somewhere along the way.
