### ISSUE TITLE
How can we make a tabular view for the list of the ordered products?

### ISSUE THREAD

**Issue by paul122297** [NielsLeenheer/EscPosEncoder#31]
The package is very similar with [node-escpos](https://www.npmjs.com/package/escpos) but the advantage of this package is that you can use it directly to your Web App and print using a thermal printer with Web Bluetooth API, unlike the [node-escpos](https://www.npmjs.com/package/escpos) it is not design to be used directly with your web app, unless you use [express.js](https://github.com/song940/node-escpos/tree/v3/examples/web). But they have a complete set of features that can be use to your nodejs project like the table feature which is the one that was currently missing on this package.

Is there a way to achieve the output below? Or is there an upcoming updates in the future for this?

![javascript-print-esc-pos-sample-receipt](https://user-images.githubusercontent.com/28916689/100830411-8b364980-349e-11eb-832a-de5838bc85ec.png)

**Comment by paul122297** [comment]
I have tried [html-to-text](https://www.npmjs.com/package/html-to-text) package to produce a table and it works, but the problem is that the align="right" and column width is not working when it was converted into text.  Please see the image below

![20201203_115613](https://user-images.githubusercontent.com/28916689/100962402-373f6980-355f-11eb-81d2-fd95812de43f.jpg)

**Comment by mariapaulinar** [comment]
Maybe this code can help you (It was made with Angular):

        const encoder = new EscPosEncoder();
        let result = encoder
          .codepage('cp852')
          .newline()
          .newline()
          .align('center')
          .line('Recibo de caja')
          .bold(true)
          .line('FACTURA     SALDO        PAGO')
          .bold(false);
        const maxChar = 11;
        for (const item of resp.facturas) {
          const cantFactura = (item.numeroFactura.toString().length <= maxChar) ? maxChar - item.numeroFactura.toString().length : 0;
          const cantSaldo = (formatNumber(item.saldo, 'en-US').length <= maxChar) ? maxChar - formatNumber(item.saldo, 'en-US').length : 0;
          const cantPago = (formatNumber(item.valorConsignar, 'en-US').length <= maxChar) ? maxChar - formatNumber(item.valorConsignar, 'en-US').length : 0;
          const line = item.numeroFactura + ' '.repeat(cantFactura) + ' $' + formatNumber(item.saldo, 'en-US') + ' '.repeat(cantSaldo) + ' $' + formatNumber(item.valorConsignar, 'en-US') + ' '.repeat(cantPago);
          result = result.line(line);
        }
        result = result
          .line('-------------------------------')
          .line('TOTAL PAGADO ' + resp.totalPagado)
          .newline()
          .newline()
          .line('Formas Pago')
          .line('-------------------------------');
        for (const item of resp.formasPago) {
          result = result.line(item.tipo + '   $' + item.valor);
        }
        result = result
          .line('-------------------------------')
          .line('TOTAL PAGADO ' + resp.totalPagado)
          .newline()
          .newline()
          .newline()
          .encode();

**Comment by NielsLeenheer** [comment]
What I've been doing is similar to @mariapaulinar. Set a maximum number of characters for a line and do the formatting yourself. Determine the length of the left string, and the right string and calculate the number of spaces you must insert between them. 

It works. But having a table feature would definitely be easier. If I can find some time, I'll look into adding more advanced layout methods.

**Comment by paul122297** [comment]
Hi, @mariapaulinar your code example was very helpful. Thank you

Yes, it will be easier if you have this feature. @NielsLeenheer

**Comment by NielsLeenheer** [comment]
The next version of EscPosEncoder will support tables with a syntax similar to this:

```
    let result = encoder
        .table(
            [
                { width: 36, marginRight: 2, align: 'left' },
                { width: 10, align: 'right' }
            ], 
            [
                [ 'Item 1', '€ 10,00' ],
                [ 'Item 2', '15,00' ],
                [ 'Item 3', '9,95' ],
                [ 'Item 4', '4,75' ],
                [ 'Item 5', '211,05' ],
                [ '', '='.repeat(10) ],
                [ 'Total', (encoder) => encoder.bold().text('€ 250,75').bold() ],
            ]
        )	
        .encode()
```
