### ISSUE TITLE
How to print Cyrillic text

### ISSUE THREAD

**Issue by morozenkomv** [NielsLeenheer/EscPosEncoder#32]
Is there a way to print Cyrillic text using this package? I tried to use  many variants, but got question marks or unreadable text. Please help me with this issue.

not worked for me
`let result = encoder.codepage('cp866').text('Привет мир')`
`let result = encoder.codepage('windows1251').text('Привет мир')`

**Comment by mariapaulinar** [comment]
Maybe this info can help you:

![image](https://user-images.githubusercontent.com/1920342/102034644-8b7ef080-3d8c-11eb-9652-b7280d717cda.png)

**Comment by morozenkomv** [comment]
After a dozens of attempts I found a workaround. It looks strange but works.
`this.printerEncoder.codepage('cp936').text('')
      .codepage('cp866').text('Предохранитель');`

**Comment by NielsLeenheer** [comment]
That is so weird. CP936 is for Chinese characters.
