### ISSUE TITLE
How to Add the Left Margin using this library

### ISSUE THREAD

**Issue by skpetks** [NielsLeenheer/EscPosEncoder#35]
i implemented Margin but its not working ,can you provide the sample code 
for add left margin bases on pixel or character

**Comment by mariapaulinar** [comment]
You can use repeat function at the left. For example:

      let margin = ' '.repeat(10);
      const encoder = new EscPosEncoder();
      const result = encoder
              .initialize()
              .align('left')
              .text(margin + 'Lorem ipsum dolor sit amet, consectetur adipiscing elit')
              .align('center')
              .text('Aliquam eget sem in nunc tincidunt blandit eu at mauris')
              .encode();
