### ISSUE TITLE
How to send ECS/Command for open Cash Drawer

### ISSUE THREAD

**Issue by novanweb** [NielsLeenheer/EscPosEncoder#37]
Hello Niels,

How to send ECS-POS Command for open cash drawer?
I use ionic 5 and bluetooth-serial plugin

Thanks

**Comment by NielsLeenheer** [comment]
I'll add a method for this in a future version. 

But you can also add do it using the raw() method and specify the ESC/POS codes yourself:

```
    // Drawer 1
   .raw([ 0x1b, 0x70, 0x00, 0x32, 0xfa ])

    // Drawer 2
   .raw([ 0x1b, 0x70, 0x01, 0x32, 0xfa ])
```

**Comment by NielsLeenheer** [comment]
The upcoming version of EscPosEncoder will support this with the pulse() command.
