### ISSUE TITLE
Print large text (bigger than normal)

### ISSUE THREAD

**Issue by MarkDsantos** [NielsLeenheer/EscPosEncoder#38]
Hi.
Thanks for the great plugin.
My print layout needs to print large text in addition to small and normal text. 
I have been searching, but with no luck.
Something similar to the following image. Sorry for low res image.
Any help appreciated.
<img width="172" alt="i1" src="https://user-images.githubusercontent.com/9959983/108841768-4c77e180-75fe-11eb-8206-82af6406ee1b.png">

**Comment by MarkDsantos** [comment]
Sorry for adding to the tickets, was able to get it done. Incase someone is looking, try using the sequence 
0x1d, 0x21, 0x02 (last one increases the size)

**Comment by hoanganhnh2009** [comment]
> Sorry for adding to the tickets, was able to get it done. Incase someone is looking, try using the sequence
> 0x1d, 0x21, 0x02 (last one increases the size)

can you help me? example
