### ISSUE TITLE
Use multiple raw commands at same time

### ISSUE THREAD

**Issue by paluchi** [NielsLeenheer/EscPosEncoder#46]
im trying to printer a double width and double height text which decimal commands are 27 33 32 and 27 33 16 respectively.

i have tried:
.raw([27, 33, 16]).raw([27, 33, 32]) (JUST MAKE A DOUBLE WIDTH, BECAUSE IT IS THE LAST ONE)

then i tried:
.raw([27, 33, 16],[27, 33, 32])

and:
.raw([27, 33, 16, 32])

and:
.raw([27, 33, 16, 27, 33, 32])

nothing works... any clue? thx you so much

**Comment by NielsLeenheer** [comment]
The raw() method accepts a single array as parameters. That array must include the bytes for one or more ESC/POS commands. And it is possible to use the raw() method multiple times.

So both are correct and identical:
```
   .raw([27, 33, 16]).raw([27, 33, 32])
   .raw([27, 33, 16, 27, 33, 32])
```

Whether or not the printer accepts these raw commands is a different matter.
