### ISSUE TITLE
Change font size?

### ISSUE THREAD

**Issue by SamuelMichelRiad** [NielsLeenheer/EscPosEncoder#47]
Great project, thanks for your efforts. Does anyone know if it's possible to increase/decrease the font size?

**Comment by paluchi** [comment]
Hi Samuel. 
Check my issue: https://github.com/NielsLeenheer/EscPosEncoder/issues/46#issue-899084125.
There y show the raw() function commands you should use to increase the font size, but i dont know how to increase it in width and height at the same time.
Tell me if you know how! good luck

**Comment by KamauIan** [comment]
@SamuelMichelRiad  and @paluchi The only way I've found is to increase font size is:
`
.raw([[0x1b, 0x21, 0x10]])   // Double both height
.raw([[0x1b, 0x21, 0x20]])   // Double both width
.raw([[0x1b, 0x21, 0x30]])   // Double both height and width
`

**Comment by paluchi** [comment]
@Kamaulan thx  you so much! 
can i ask you how did you notice that [0x1b, 0x21, 0x30] would work?  whats 0x30 reffers to?

**Comment by paluchi** [comment]
> @SamuelMichelRiad and @paluchi The only way I've found is to increase font size is:
> `.raw([[0x1b, 0x21, 0x10]]) // Double both height`
> `.raw([[0x1b, 0x21, 0x20]]) // Double both width`
> `.raw([[0x1b, 0x21, 0x30]]) // Double both height and width`

thx  you so much! 
can i ask you how did you notice that [0x1b, 0x21, 0x30] would work?  whats 0x30 reffers to?

**Comment by paluchi** [comment]
@KamauIan 
thx you so much!
can i ask you how did you notice that [0x1b, 0x21, 0x30] would work? whats 0x30 reffers to?

**Comment by KamauIan** [comment]
@paluchi checkout these resources for more : 
https://github.com/escpos/escpos/blob/master/lib/escpos.rb
https://escpos.readthedocs.io/en/latest/font_cmds.html#select-print-mode-1b-21-rel-phx

**Comment by NielsLeenheer** [comment]
The upcoming 2.0 version of EscPosEncoder will support changing the width and height of the text:
```
encoder
   .width(3)
   .height(3)
   .text('This text is three times as large as normal')
   ```

**Comment by lajith111** [comment]
@NielsLeenheer is there any size between hight(1). And hight(2) because hight (2) is little large.. please let me know is there any alternative solutions thanks
