### ISSUE TITLE
QR code encoded but not printing with 340 characters.

### ISSUE THREAD

**Issue by munkh-altai** [NielsLeenheer/EscPosEncoder#6]
Thank for very useful library.

I am writing mobile POS app in nativescript.

and i use your encoder. QR code encoded but not printing with 340 characters ?

do you have any solution for long text  #qrcode?

**Comment by NielsLeenheer** [comment]
The most likely answer is that your printer does not support qrcodes with that many characters. While there is not a size limit in the specification, individual printers may impose a limit of their own. I for example have a printer that refuses to print anything larger than 255 characters.

**Comment by tresf** [comment]
To @NielsLeenheer's point, the 255 limit is surpassed here: https://github.com/NielsLeenheer/EscPosEncoder/blob/55f5513deb7b89401d6e24b9fc2498f6f77b48ab/src/esc-pos-encoder.js#L428

The fourth parameter should allow values over 255.  We have near identical logic here: https://github.com/qzind/tray/wiki/2.0-Raw-Printing#escpos-qr-code

If the hardware can't go over 255, you can render the QR code as an image using 3rd party libraries and send the image data to the ESCPOS printer instead.
