### ISSUE TITLE
For each command, codepage name is printed

### ISSUE THREAD

**Issue by rborovina** [NielsLeenheer/EscPosEncoder#61]
Instead of text, printer prints out the codepage name, like 'ascii' or 'cp850'.

**Comment by Grentry** [comment]
I have the same problem did u find a solution?

**Comment by Grentry** [comment]
i found the bug the paramaters for CodepageEncoder.encode should be swaped.

**Comment by ZarooDotnet** [comment]
pls give me an example, cause I can't complete, it and i tried a lot of time, and get bored
and thank u

**Comment by EnjoX** [comment]
`  _encode(value) {
    if (this._codepage != 'auto') {
      return CodepageEncoder.encode(value, this._codepage);
    }

    let codepages;

    if (typeof this._options.codepageMapping == 'string') {
      codepages = codepageMappings[this._options.codepageMapping];
    } else {
      codepages = this._options.codepageMapping;
    }

    const fragments = CodepageEncoder.autoEncode(value, this._options.codepageCandidates);

    let length = 0;
    for (let f = 0; f < fragments.length; f++) {
      length += 3 + fragments[f].bytes.byteLength;
    }

    const buffer = new Uint8Array(length);
    let i = 0;

    for (let f = 0; f < fragments.length; f++) {
      buffer.set([0x1b, 0x74, codepages[fragments[f].codepage]], i);
      buffer.set(fragments[f].bytes, i + 3);
      i += 3 + fragments[f].bytes.byteLength;

      this._state.codepage = codepages[fragments[f].codepage];
    }

    return buffer;
  }`
  
this line should be 
  return CodepageEncoder.encode(this._codepage, value);

**Comment by ZarooDotnet** [comment]
I'll try thanks a lot..for ur response

**Comment by ZarooDotnet** [comment]
Hi..
I print english successfully..but arabic get unreadable letters,while I tried different codepage
Note my printer is xprinter..
Any help..pls

**Comment by EnjoX** [comment]
you need to check which codepages your printer supports and the use one with arabic letters

**Comment by AlhassanMousa** [comment]
> Hi.. I print english successfully..but arabic get unreadable letters,while I tried different codepage Note my printer is xprinter.. Any help..pls

same here

**Comment by NielsLeenheer** [comment]
This should be resolved when an update to CodePageEncoder is released (together with the release of EscPosEncoder).
