### ISSUE TITLE
Print image with React Native

### ISSUE THREAD

**Issue by hoanganhnh2009** [NielsLeenheer/EscPosEncoder#63]
How to print image base 64 width React Native

**Comment by tr3v3r** [comment]
@hoanganhnh2009 hello! If you need to print using Epson printer you can try this lib - https://www.npmjs.com/package/react-native-esc-pos-printer

**Comment by hoanganhnh2009** [comment]
Thankyou but i used some printer: Xprinter, Gprinter, Antech Printer, etc...
