### ISSUE TITLE
Any news on releasing version 2.0 ?

### ISSUE THREAD

**Issue by dmastag** [NielsLeenheer/EscPosEncoder#64]
The new Tables feature looks promising, but noticed that its not released yet.

**Comment by hoanganhnh2009** [comment]
He promised in the next few weeks, but it's been months now and still no release

**Comment by dmastag** [comment]
Yes, that is unfortunate

**Comment by sergeu90** [comment]
Any updates?

**Comment by hoanganhnh2009** [comment]
i waiting it a long time, but now not still update

**Comment by lajith111** [comment]
Any update on 2.0

**Comment by NielsLeenheer** [comment]
Soon... Very soon.
