### ISSUE TITLE
Please Include CP874 IN REACT NATIVE EscPosEncoder 

### ISSUE THREAD

**Issue by chukiatt** [NielsLeenheer/EscPosEncoder#65]
@NielsLeenheer
I am stuck my project a lot of day, i found your EscPosEncoder that work for me but i cannot print thai in my epson thermal printer ,

i found in file esc-pos-encoder.js

codepage(value) {
const codepages = {
'cp437': [0x00, false],
'cp737': [0x40, false],
'cp850': [0x02, false],

not include cp874 but i need to use this codepage because all of epson pos printers are support thai 3 pass character in cp874
Please Help me .

Please...

**Comment by NielsLeenheer** [comment]
cp874 should be included in the upcoming EscPosEncoder 2.0 release.
