### ISSUE TITLE
Not Printing English

### ISSUE THREAD

**Issue by mfaheemakhtar** [NielsLeenheer/EscPosEncoder#7]
Hi, I'm using this module with "QS-5801" printer in React Native. It is printing everything in Chinese characters. Barcode and QR are also not working.

I've tried different codepages, but no luck.

Is there something I'm missing?

Thanks

P.S. This module works but is not printing Barcode and QR 
https://github.com/ingoncalves/escpos-xml

**Comment by NielsLeenheer** [comment]
Could you give an example of the code you are using?

**Comment by mfaheemakhtar** [comment]
@NielsLeenheer , I tried printing Barcode and QR by directly sending ESC commands to the printer, seems like it does not support them.

Regarding the Chinese characters, I have found that the Prototype of encoded result is TypedArray and it does not have a toString function.

I was able to print English characters by creating a small function to convert the Uint8Array to string.

Thanks

**Comment by mfaheemakhtar** [comment]
Hi, sorry I was not clear.

I'm using a bluetooth library to send commands to the printer. That library uses toString() to convert the array to base64, the base64 is then decoded at the native code and sent to the printer.

One reason could be "beacause react native is currently not capable of passing buffer directly to native methods. "

Thanks for the great library.
