### ISSUE TITLE
New npm package

### ISSUE THREAD

**Issue by Grentry** [NielsLeenheer/EscPosEncoder#71]
Hi

Is it possible to create a npm package with the newest version?
Or does someone have a fork package with the newest version?

best regards

**Comment by LukasKlement** [comment]
Follow-up on this, would it be possible to update the package on npmjs (https://www.npmjs.com/package/esc-pos-encoder)? The code on the master branch has several new features which are essential, e.g. width(), height(), invert()

**Comment by Grentry** [comment]
I created a package for me if you want you can use it

https://www.npmjs.com/package/enjox-esc-pos-encoder

i also fixed an encoding error i think but im not 100% sure but i use it in an app so its working

**Comment by yooouuri** [comment]
@Grentry just use

`pnpm add https://github.com/NielsLeenheer/EscPosEncoder` Or whatever package manager you're using

It will use the `dist` folder in the repo itself.

![image](https://user-images.githubusercontent.com/12934957/216944244-a169c192-7e2f-4a3f-a457-6fb9956c387b.png)

**Comment by NielsLeenheer** [comment]
The release of EscPosEncoder 2 is coming very soon...

**Comment by MarkPhsd** [comment]
Will the new release include producing table-like structures?

**Comment by NielsLeenheer** [comment]
Yes, it will.

**Comment by NielsLeenheer** [comment]
EscPosEncoder 2 has been released!
