### ISSUE TITLE
Cannot install on M1 Mac (ARM64)

### ISSUE THREAD

**Issue by guidoffm** [NielsLeenheer/EscPosEncoder#73]
The module uses `canvas`. Canvas itself seems to rely on Python. 
This gives me a lot of ugly `gyp` errors and the dependency cannot be installed.

**Comment by guidoffm** [comment]
I found a solution for the problem here:

https://stackoverflow.com/questions/64562563/how-can-i-ovecome-this-error-in-npm-install

`brew install pkg-config cairo pango libpng jpeg giflib librsvg`

Maybe it is a good idea to add this information to the documentation.

For my needs this is too heavy since I do not need graphics.

**Comment by chukiatt** [comment]
Thank you
