### ISSUE TITLE
Images printed are always black background

### ISSUE THREAD

**Issue by lovelyelfpop** [NielsLeenheer/EscPosEncoder#9]
Even if the images are white background jpg, or transparent background png.

**Comment by lovelyelfpop** [comment]
Solution: https://github.com/znzn40/EscPosEncoder/commit/d1166f0dd6ab84aa28683ac2eb9a2b69063084c8

**Comment by NielsLeenheer** [comment]
Not sure how this happened, as the version of EscPosEncoder that I used before releasing it as open source didn't have this issue. Fixed in release 1.2.0.
