### ISSUE TITLE
Image printed with empty spaces in between

### ISSUE THREAD

**Issue by 5r1m** [NielsLeenheer/EscPosEncoder#99]
Firstly thank you for this wonderful library!

I am trying to print an image but how ever I see that there are spaces in between images. Tried with different images but problem remains the same. 

Actual image:
<img width="162" alt="Screenshot 2023-12-19 at 5 11 44 PM" src="https://github.com/NielsLeenheer/EscPosEncoder/assets/47805716/74e9fd9a-8fec-4fb4-be7b-7c89c2604f73">

Printed copy:
![IMG_0014](https://github.com/NielsLeenheer/EscPosEncoder/assets/47805716/3f76ff40-c353-44c4-b94f-be153c519b4a)

I have used the code below to print image:
let img = new Image();
img.src = 'https://...';

img.onload = function() {
    let result = encoder
        .image(img, 480, 480, 'atkinson')
        .encode()
}

Does this required any additional flags to be set? Tried with different images and 2 printers and the result is same. 

Thanks in advance

**Comment by chidera-ugo** [comment]
try changing the imageMode to raster

**Comment by 5r1m** [comment]
Thank you @chidera-ugo. Yes this was the problem. Some how the printer which I am using seems to be based on older version and didn't realise that I need to changed the mode. There is still a very minute line which I can see but its lot better now.
